export const GET_USERS_DATA_REQUEST = 'GET_USERS_DATA_REQUEST'
export const GET_USERS_DATA_SUCCESS = 'GET_USERS_DATA_SUCCESS'
export const GET_USERS_DATA_FAILURE = 'GET_USERS_DATA_FAILURE'

export const GET_FOLLOW_USER_REQUEST = 'GET_FOLLOW_USER_REQUEST'
export const GET_FOLLOW_USER_SUCCESS = 'GET_FOLLOW_USER_SUCCESS'
export const GET_FOLLOW_USER_FAILURE = 'GET_FOLLOW_USER_FAILURE' 

export const GET_UNFOLLOW_USER_REQUEST = 'GET_UNFOLLOW_USER_REQUEST'
export const GET_UNFOLLOW_USER_SUCCESS = 'GET_UNFOLLOW_USER_SUCCESS'
export const GET_UNFOLLOW_USER_FAILURE = 'GET_UNFOLLOW_USER_FAILURE'  

export const GET_BLOCK_USER_REQUEST = 'GET_BLOCK_USER_REQUEST'
export const GET_BLOCK_USER_SUCCESS = 'GET_BLOCK_USER_SUCCESS'
export const GET_BLOCK_USER_FAILURE = 'GET_BLOCK_USER_FAILURE'

export const GET_ADD_FOLLOWING_REQUEST = 'GET_ADD_FOLLOWING_REQUEST'
export const GET_ADD_FOLLOWING_SUCCESS = 'GET_ADD_FOLLOWING_SUCCESS' 
export const GET_ADD_FOLLOWING_FAILURE = 'GET_ADD_FOLLOWING_FAILURE'

export const GET_UNFOLLOWING_REQUEST = 'GET_UNFOLLOWING_REQUEST'
export const GET_UNFOLLOWING_SUCCESS = 'GET_UNFOLLOWING_SUCCESS'
export const GET_UNFOLLOWING_FAILURE = 'GET_UNFOLLOWING_FAILURE'

export const GET_SHOW_ALL_USERS_REQUEST = 'GET_SHOW_ALL_USERS_REQUEST'
export const GET_SHOW_ALL_USERS_SUCCESS = 'GET_SHOW_ALL_USERS_SUCCESS'
export const GET_SHOW_ALL_USERS_FAILURE = 'GET_SHOW_ALL_USERS_FAILURE'

// export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// mport { GET_USERS_DATA_REQUEST, GET_USERS_DATA_SUCCESS, GET_USERS_DATA_FAILURE } from "../constants/constants";